### ISSUE TITLE
Abbreviated IAS with Letter

### ISSUE THREAD

**Issue by K0nnyy** [MorpheusXAUT/IASsure#5]
It would be nice to have an IAS Tag item with both 2 numbers and the letter, because the german tower radar shows IAS as "I21"  

Possible implementations would be:
Entry in config to limit the numbers for the complete IAS to display (same as MACH)
Entry in config to enable letter with abbreviated TAG option

**Comment by MorpheusXAUT** [comment]
This can currently be achieved by using the [`Calculated IAS (abbreviated)`](https://github.com/MorpheusXAUT/IASsure#calculated-ias-abbreviated) and adding a `Static string` tag item **without** a separator before it:
![example tag setup](https://i.imgur.com/WG5Pnel.png)

Resolving as `wontdo` for now.
