### ISSUE TITLE
BUG: Missing tag item Calculated Mach (togglable)

### ISSUE THREAD

**Issue by becas22** [MorpheusXAUT/IASsure#7]
The only togglable Mach tag item it's the Calculated Mach (above threshold, togglable)

https://github.com/MorpheusXAUT/IASsure/commit/b11d470f1523cbd7e1ffbf672e3a156cb15e3470#diff-a9df7f9fc5c73a5d20de56685ef8e9577ccf22ee8e758fd0cb97990f02b6bcbcL279

**Comment by MorpheusXAUT** [comment]
Fixed in [v1.4.2](https://github.com/MorpheusXAUT/IASsure/releases/tag/v1.4.2).
