### ISSUE TITLE
Feature request: Make a new click function for unreliable DAPs

### ISSUE THREAD

**Issue by becas22** [MorpheusXAUT/IASsure#8]
Currently for unreliable DAPs you can use the reported IAS/mach menu and then obtain an offset. This works OK for enroute assuming the track change is not that big but it does not work for APP or TWR.

My suggestion would be to make a new click function that either:

- Replace the DAP with an icon that makes it identifiable as unreliable. For example `#`, as this is the real symbol for missing DSFL (missing DIAS or DMACH icon does not exist) - I would say this is the prefered way

- Change the color of the DAP to signal the ATC that it is unreliable (might cause problems with sector states, emergencies, etc)

**Comment by MorpheusXAUT** [comment]
Implemented in [v1.5.0](https://github.com/MorpheusXAUT/IASsure/releases/tag/v1.5.0).
